# -*- coding: utf-8 -*-
"""clinical trial analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d091-gl_a85tBiIeEfR5eiIEV0yB2COb
"""

#loading the datasets
from google.colab import files

uploaded = files.upload()

participants = pd.read_csv("participants.csv")
visits = pd.read_csv("visits.csv")
treatment_assignments = pd.read_csv("treatment_assignments.csv")
lab_results = pd.read_csv("lab_results.csv")
adverse_events = pd.read_csv("adverse_events.csv")
medication_adherence = pd.read_csv("medication_adherence.csv")
trial_sites = pd.read_csv("trial_sites.csv")
products = pd.read_csv("products.csv")

print("Participants:", participants.shape)
print("Visits:", visits.shape)
print("Treatment Assignments:", treatment_assignments.shape)
print("Lab Results:", lab_results.shape)
print("Adverse Events:", adverse_events.shape)
print("Medication Adherence:", medication_adherence.shape)
print("Trial Sites:", trial_sites.shape)
print("Products:", products.shape)

#missing value check
print("Participants:")
print(participants.head())

print("\nMissing values in participants:")
print(participants.isnull().sum())

## A/B statistical test

# Number of responders and participants
control_success = 2183
control_total = 5000

treatment_success = 3620
treatment_total = 5000

# Response rates
control_rate = control_success / control_total
treatment_rate = treatment_success / treatment_total

# Difference in response rates
difference = treatment_rate - control_rate

# Pooled response rate
pooled_rate = (
    control_success + treatment_success
) / (
    control_total + treatment_total
)

# Standard error
standard_error = np.sqrt(
    pooled_rate * (1 - pooled_rate) *
    (1 / control_total + 1 / treatment_total)
)

# Z statistic
z_score = difference / standard_error

# Two-sided p-value
p_value = 2 * (1 - stats.norm.cdf(abs(z_score)))

print("Control response rate:", round(control_rate * 100, 2), "%")
print("Treatment response rate:", round(treatment_rate * 100, 2), "%")
print("Treatment effect:", round(difference * 100, 2), "percentage points")
print("Z-score:", round(z_score, 2))
print("P-value:", p_value)

#Confidence interval

# Standard error for the difference in response rates
standard_error_ci = np.sqrt(
    (treatment_rate * (1 - treatment_rate) / treatment_total)
    +
    (control_rate * (1 - control_rate) / control_total)
)

# 95% confidence interval
margin_of_error = 1.96 * standard_error_ci

lower = difference - margin_of_error
upper = difference + margin_of_error

print("Treatment effect:", round(difference * 100, 2), "percentage points")
print("95% CI lower:", round(lower * 100, 2), "percentage points")
print("95% CI upper:", round(upper * 100, 2), "percentage points")

## practical significance

# Relative improvement
relative_improvement = (
    (treatment_rate - control_rate) / control_rate
) * 100

# Number needed to treat
absolute_difference = treatment_rate - control_rate
number_needed_to_treat = 1 / absolute_difference

print("Relative improvement:", round(relative_improvement, 2), "%")
print("Absolute improvement:", round(absolute_difference * 100, 2), "percentage points")
print("Number needed to treat:", round(number_needed_to_treat, 2))

##Outcome change distributions

control_change = participants[
    participants["Treatment_Arm"] == "Control"
]["Outcome_Change"]

treatment_change = participants[
    participants["Treatment_Arm"] == "Treatment"
]["Outcome_Change"]

print("Control average outcome change:",
      round(control_change.mean(), 2))

print("Treatment average outcome change:",
      round(treatment_change.mean(), 2))

print("Control median outcome change:",
      round(control_change.median(), 2))

print("Treatment median outcome change:",
      round(treatment_change.median(), 2))

## testing outcome-change difference statistically
t_stat, p_value_change = stats.ttest_ind(
    treatment_change,
    control_change,
    equal_var=False
)

print("T-statistic:", round(t_stat, 2))
print("P-value:", p_value_change)

# visualisation
response_rates = participants.groupby("Treatment_Arm")["Response_Status"].apply(
    lambda x: (x == "Responder").mean() * 100
)

plt.figure(figsize=(7, 5))

plt.bar(
    response_rates.index,
    response_rates.values
)

plt.title("Treatment vs Control Response Rate")
plt.xlabel("Treatment Arm")
plt.ylabel("Response Rate (%)")

for i, value in enumerate(response_rates.values):
    plt.text(i, value + 1, f"{value:.1f}%", ha="center")

plt.ylim(0, 100)
plt.show()

#Adverse event rate by treatment arm

# Participants with at least one adverse event
participants_with_event = (
    adverse_events["Participant_ID"]
    .nunique()
)

# Participants with adverse events by treatment arm
event_participants = (
    adverse_events
    .merge(
        participants[["Participant_ID", "Treatment_Arm"]],
        on="Participant_ID",
        how="left"
    )
    .groupby("Treatment_Arm")["Participant_ID"]
    .nunique()
)

# Total participants in each arm
total_participants = participants.groupby("Treatment_Arm")["Participant_ID"].nunique()

# Adverse event rate
adverse_event_rate = (
    event_participants / total_participants * 100
)

print("Adverse event rate by treatment arm:")
print(adverse_event_rate.round(2))

#Testing whether the adverse-event difference is statistically significant
control_events = event_participants["Control"]
treatment_events = event_participants["Treatment"]

control_no_events = total_participants["Control"] - control_events
treatment_no_events = total_participants["Treatment"] - treatment_events

table = [
    [control_events, control_no_events],
    [treatment_events, treatment_no_events]
]

chi2, p_value_ae, dof, expected = stats.chi2_contingency(table)

print("Chi-square statistic:", round(chi2, 2))
print("P-value:", p_value_ae)

#Analyze medication adherence
adherence_summary = (
    medication_adherence["Adherence_Band"]
    .value_counts()
    .sort_index()
)

print(adherence_summary)

#Does adherence relate to treatment response?
adherence_response = medication_adherence.merge(
    participants[["Participant_ID", "Response_Status"]],
    on="Participant_ID",
    how="left"
)

adherence_response_rate = (
    adherence_response
    .groupby("Adherence_Band")["Response_Status"]
    .apply(lambda x: (x == "Responder").mean() * 100)
    .sort_index()
)

print("Response rate by adherence:")
print(adherence_response_rate.round(2))

#Testing whether adherence bands are associated with response
adherence_table = pd.crosstab(
    adherence_response["Adherence_Band"],
    adherence_response["Response_Status"]
)

print(adherence_table)

chi2, p_value_adherence, dof, expected = stats.chi2_contingency(
    adherence_table
)

print("\nChi-square:", round(chi2, 2))
print("P-value:", p_value_adherence)

#Subgroup analysis: baseline severity
severity_response = (
    participants
    .groupby(["Baseline_Severity", "Treatment_Arm"])["Response_Status"]
    .apply(lambda x: (x == "Responder").mean() * 100)
    .reset_index(name="Response_Rate")
)

print(severity_response)

#Calculate the subgroup treatment effects automatically
severity_pivot = severity_response.pivot(
    index="Baseline_Severity",
    columns="Treatment_Arm",
    values="Response_Rate"
)

severity_pivot["Treatment_Effect"] = (
    severity_pivot["Treatment"]
    - severity_pivot["Control"]
)

print(severity_pivot.round(2))

#subgroup visualization
severity_pivot[["Control", "Treatment"]].plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Response Rate by Baseline Severity")
plt.xlabel("Baseline Severity")
plt.ylabel("Response Rate (%)")
plt.xticks(rotation=0)
plt.legend(title="Treatment Arm")
plt.ylim(0, 100)
plt.show()

#Risk-category subgroup analysis
risk_response = (
    participants
    .groupby(["Risk_Category", "Treatment_Arm"])["Response_Status"]
    .apply(lambda x: (x == "Responder").mean() * 100)
    .reset_index(name="Response_Rate")
)

print(risk_response)

#final Python summary table
final_summary = pd.DataFrame({
    "Metric": [
        "Control Response Rate",
        "Treatment Response Rate",
        "Treatment Effect",
        "95% CI Lower",
        "95% CI Upper",
        "A/B Test P-Value",
        "Relative Improvement",
        "Number Needed to Treat",
        "Control Average Outcome Change",
        "Treatment Average Outcome Change",
        "Adverse Event Rate - Control",
        "Adverse Event Rate - Treatment",
        "Adverse Event P-Value"
    ],
    "Value": [
        control_rate * 100,
        treatment_rate * 100,
        difference * 100,
        lower * 100,
        upper * 100,
        p_value,
        relative_improvement,
        number_needed_to_treat,
        control_change.mean(),
        treatment_change.mean(),
        adverse_event_rate["Control"],
        adverse_event_rate["Treatment"],
        p_value_ae
    ]
})

print(final_summary.round(2))

## Save final statistical summary
final_summary.to_csv(
    "clinical_trial_statistical_summary.csv",
    index=False
)

# Save severity subgroup results
severity_pivot.round(2).to_csv(
    "clinical_trial_severity_subgroups.csv"
)

print("Files saved successfully.")

