CREATE DATABASE CLINICAL_TRIAL_ANALYTICS;
USE DATABASE CLINICAL_TRIAL_ANALYTICS;

CREATE TABLE PARTICIPANTS (
    PARTICIPANT_ID VARCHAR,
    SITE_ID VARCHAR,
    AGE NUMBER,
    GENDER VARCHAR,
    BASELINE_SEVERITY VARCHAR,
    RISK_CATEGORY VARCHAR,
    TREATMENT_ARM VARCHAR,
    BASELINE_SCORE FLOAT,
    ENDPOINT_SCORE FLOAT,
    OUTCOME_CHANGE FLOAT,
    RESPONSE_STATUS VARCHAR
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.VISITS (
    PARTICIPANT_ID VARCHAR,
    VISIT_NAME VARCHAR,
    VISIT_DATE DATE
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.TREATMENT_ASSIGNMENTS (
    PARTICIPANT_ID VARCHAR,
    TREATMENT_ARM VARCHAR,
    RANDOMIZATION_DATE DATE,
    PRODUCT_CODE VARCHAR
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.LAB_RESULTS (
    PARTICIPANT_ID VARCHAR,
    LAB_TEST VARCHAR,
    VISIT VARCHAR,
    RESULT_VALUE FLOAT,
    UNIT VARCHAR
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.ADVERSE_EVENTS (
    ADVERSE_EVENT_ID VARCHAR,
    PARTICIPANT_ID VARCHAR,
    EVENT_TYPE VARCHAR,
    SEVERITY VARCHAR,
    RELATED_TO_TREATMENT VARCHAR,
    SERIOUS_EVENT VARCHAR
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.MEDICATION_ADHERENCE (
    PARTICIPANT_ID VARCHAR,
    DOSES_EXPECTED NUMBER,
    DOSES_TAKEN NUMBER,
    ADHERENCE_RATE FLOAT,
    ADHERENCE_BAND VARCHAR
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.TRIAL_SITES (
    SITE_ID VARCHAR,
    SITE_NAME VARCHAR,
    REGION VARCHAR,
    SITE_TYPE VARCHAR
);


CREATE TABLE CLINICAL_TRIAL_ANALYTICS.PUBLIC.PRODUCTS (
    PRODUCT_CODE VARCHAR,
    PRODUCT_NAME VARCHAR,
    PRODUCT_TYPE VARCHAR
);

SELECT
    TABLE_NAME,
    ROW_COUNT
FROM CLINICAL_TRIAL_ANALYTICS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME;

SELECT
    COUNT(*) AS TOTAL_PARTICIPANTS,
    COUNT(DISTINCT PARTICIPANT_ID) AS UNIQUE_PARTICIPANTS,
    COUNT_IF(PARTICIPANT_ID IS NULL) AS MISSING_PARTICIPANT_ID,
    COUNT_IF(TREATMENT_ARM IS NULL) AS MISSING_TREATMENT_ARM,
    COUNT_IF(AGE IS NULL) AS MISSING_AGE,
    COUNT_IF(BASELINE_SCORE IS NULL) AS MISSING_BASELINE_SCORE,
    COUNT_IF(ENDPOINT_SCORE IS NULL) AS MISSING_ENDPOINT_SCORE,
    COUNT_IF(OUTCOME_CHANGE IS NULL) AS MISSING_OUTCOME_CHANGE
FROM CLINICAL_TRIAL_ANALYTICS.PUBLIC.PARTICIPANTS;

SELECT
    TREATMENT_ARM,
    COUNT(*) AS PARTICIPANTS,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS PERCENT_OF_TRIAL
FROM CLINICAL_TRIAL_ANALYTICS.PUBLIC.PARTICIPANTS
GROUP BY TREATMENT_ARM
ORDER BY TREATMENT_ARM;

SELECT
    ROUND(
        (
            COUNT_IF(TREATMENT_ARM = 'Treatment' AND RESPONSE_STATUS = 'Responder') * 100.0
            / COUNT_IF(TREATMENT_ARM = 'Treatment')
        ) -
        (
            COUNT_IF(TREATMENT_ARM = 'Control' AND RESPONSE_STATUS = 'Responder') * 100.0
            / COUNT_IF(TREATMENT_ARM = 'Control')
        ),
        2
    ) AS TREATMENT_EFFECT_PP
FROM CLINICAL_TRIAL_ANALYTICS.PUBLIC.PARTICIPANTS;


SELECT
    TREATMENT_ARM,
    COUNT(*) AS TOTAL_PARTICIPANTS,
    COUNT_IF(RESPONSE_STATUS = 'Responder') AS RESPONDERS,
    COUNT_IF(RESPONSE_STATUS = 'Non-Responder') AS NON_RESPONDERS,
    ROUND(
        COUNT_IF(RESPONSE_STATUS = 'Responder') * 1.0 / COUNT(*),
        4
    ) AS RESPONSE_RATE
FROM CLINICAL_TRIAL_ANALYTICS.PUBLIC.PARTICIPANTS
GROUP BY TREATMENT_ARM
ORDER BY TREATMENT_ARM;